# Generated by Django 5.2.11 on 2026-08-11 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('term_months', models.PositiveSmallIntegerField(default=12)),
                ('risk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('decision', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='clients.client')),
            ],
        ),
    ]
