# Generated by Django 5.2.11 on 2026-08-11 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.PositiveIntegerField()),
                ('duree_mois', models.PositiveSmallIntegerField(default=12)),
                ('score_risque', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('niveau_risque', models.CharField(blank=True, max_length=20)),
                ('decision_agent', models.CharField(default='EN_ATTENTE', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_credit', to='clients.client')),
            ],
        ),
    ]
