# Generated by Django 5.2.11 on 2026-08-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_demandeimportee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=120)),
                ('montant_min', models.PositiveIntegerField(default=0)),
                ('montant_max', models.PositiveIntegerField(default=0)),
                ('duree_min_mois', models.PositiveSmallIntegerField(default=0)),
                ('duree_max_mois', models.PositiveSmallIntegerField(default=0)),
                ('secteurs_vises', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='anciennete_activite_mois',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='autres_revenus_menage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='charges_activite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='charges_menage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='date_decision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='mensualite_dette_existante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='motif_decision',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='objet_credit',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='observations_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='recettes_activite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='saisonnalite_activite',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='demandecredit',
            name='decision_agent',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('A_REVOIR', 'À revoir'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='credits.produitcredit'),
        ),
    ]
