# Generated by Django 5.2.11 on 2026-08-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_produitcredit_demandecredit_anciennete_activite_mois_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandecredit',
            name='niveau_risque',
        ),
        migrations.RemoveField(
            model_name='demandecredit',
            name='score_risque',
        ),
    ]
