# Generated by Django 5.2.11 on 2026-08-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadres', '0001_initial'),
        ('credits', '0006_remove_demandecredit_niveau_risque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='cadre_analyse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='cadres.cadreanalyse'),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='valeurs_cadre',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='produitcredit',
            name='cadre_analyse',
            field=models.ForeignKey(blank=True, help_text="Méthode d'analyse financière appliquée aux demandes portant ce produit.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='cadres.cadreanalyse'),
        ),
    ]
