# Generated by Django 5.2.11 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0008_alter_activiteimportee_identifiant_source_and_more"),
        ("credits", "0007_demandecredit_cadre_analyse_and_more"),
    ]

    operations = [
        migrations.AlterField(model_name="creditimporte", name="identifiant_source", field=models.CharField(max_length=40)),
        migrations.AlterField(model_name="demandeimportee", name="identifiant_source", field=models.CharField(max_length=40)),
        migrations.AlterField(model_name="echeanceimportee", name="identifiant_source", field=models.CharField(max_length=40)),
        migrations.AlterField(model_name="paiementimporte", name="identifiant_source", field=models.CharField(max_length=40)),
        migrations.AddConstraint(model_name="creditimporte", constraint=models.UniqueConstraint(fields=("client", "identifiant_source"), name="credit_source_unique_par_client")),
        migrations.AddConstraint(model_name="demandeimportee", constraint=models.UniqueConstraint(fields=("client", "identifiant_source"), name="demande_source_unique_par_client")),
        migrations.AddConstraint(model_name="echeanceimportee", constraint=models.UniqueConstraint(fields=("credit", "identifiant_source"), name="echeance_source_unique_par_credit")),
        migrations.AddConstraint(model_name="paiementimporte", constraint=models.UniqueConstraint(fields=("credit", "identifiant_source"), name="paiement_source_unique_par_credit")),
    ]
