from django.urls import path
from .views import (
    analyser_demande_credit,
    appliquer_simulation,
    creer_client,
    detail_client,
    dossier_instruction,
    gerer_produit_credit,
    enregistrer_decision,
    enregistrer_institution,
    etat_service,
    lire_institution,
    liste_audit,
    liste_documents_client,
    liste_lots_import,
    liste_clients,
    liste_demandes_credit,
    liste_produits_credit,
    modifier_client,
    simuler_demande,
    supprimer_client,
    supprimer_document,
    televerser_document,
    tableau_bord,
    vue_portefeuille,
    vue_retards,
    valider_import_csv,
    confirmer_import_csv,
)

urlpatterns = [
    path("etat/", etat_service, name="etat-service"),
    path("tableau-bord/", tableau_bord, name="tableau-bord"),
    path("institution/", lire_institution, name="lire-institution"),
    path("institution/enregistrer/", enregistrer_institution, name="enregistrer-institution"),
    path("clients/", liste_clients, name="liste-clients"),
    path("clients/creer/", creer_client, name="creer-client"),
    path("clients/<int:identifiant_client>/", detail_client, name="detail-client"),
    path("clients/<int:identifiant_client>/modifier/", modifier_client, name="modifier-client"),
    path("clients/<int:identifiant_client>/supprimer/", supprimer_client, name="supprimer-client"),
    path("clients/<int:identifiant_client>/documents/", liste_documents_client, name="liste-documents-client"),
    path("clients/<int:identifiant_client>/documents/televerser/", televerser_document, name="televerser-document"),
    path("documents/<int:identifiant_document>/supprimer/", supprimer_document, name="supprimer-document"),
    path("produits-credit/", liste_produits_credit, name="liste-produits-credit"),
    path("produits-credit/creer/", gerer_produit_credit, name="creer-produit-credit"),
    path("produits-credit/<int:identifiant_produit>/", gerer_produit_credit, name="gerer-produit-credit"),
    path("demandes-credit/", liste_demandes_credit, name="liste-demandes-credit"),
    path("demandes-credit/analyser/", analyser_demande_credit, name="analyser-demande-credit"),
    path("demandes-credit/<int:identifiant_demande>/", dossier_instruction, name="dossier-instruction"),
    path("demandes-credit/<int:identifiant_demande>/simuler/", simuler_demande, name="simuler-demande"),
    path("demandes-credit/<int:identifiant_demande>/appliquer-simulation/", appliquer_simulation, name="appliquer-simulation"),
    path("demandes-credit/<int:identifiant_demande>/decision/", enregistrer_decision, name="enregistrer-decision"),
    path("audit/", liste_audit, name="liste-audit"),
    path("portefeuille/", vue_portefeuille, name="vue-portefeuille"),
    path("retards/", vue_retards, name="vue-retards"),
    path("imports-csv/valider/", valider_import_csv, name="valider-import-csv"),
    path("imports-csv/lots/", liste_lots_import, name="liste-lots-import"),
    path("imports-csv/confirmer/", confirmer_import_csv, name="confirmer-import-csv"),
]
