# Generated by Django 5.2.11 on 2026-08-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=160)),
                ('secteur_activite', models.CharField(max_length=80)),
                ('revenu_mensuel', models.PositiveIntegerField()),
                ('charges_mensuelles', models.PositiveIntegerField()),
                ('anciennete_activite_mois', models.PositiveIntegerField()),
                ('nombre_retards', models.PositiveSmallIntegerField(default=0)),
                ('regularite_tontine', models.CharField(default='inconnue', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
