# Generated by Django 5.2.11 on 2026-08-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('sector', models.CharField(max_length=80)),
                ('monthly_income', models.PositiveIntegerField()),
                ('monthly_expenses', models.PositiveIntegerField()),
                ('business_age_months', models.PositiveIntegerField()),
                ('late_payments', models.PositiveSmallIntegerField(default=0)),
                ('tontine_regularity', models.CharField(default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
