# Generated by Django 5.2.11 on 2026-08-13 15:04

import clients.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_activiteimportee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('piece_identite', "Pièce d'identité"), ('justificatif_activite', "Justificatif d'activité"), ('photo', 'Photo'), ('autre', 'Autre document')], max_length=40)),
                ('fichier', models.FileField(upload_to=clients.models.chemin_document)),
                ('nom_original', models.CharField(max_length=200)),
                ('taille_octets', models.PositiveIntegerField(default=0)),
                ('televerse_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
            ],
        ),
    ]
