# Generated by Django 5.2.11 on 2026-08-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_documentdossier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='charges_mensuelles',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mensualite_dette_existante',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nombre_retards',
        ),
        migrations.RemoveField(
            model_name='client',
            name='regularite_tontine',
        ),
        migrations.RemoveField(
            model_name='client',
            name='revenu_mensuel',
        ),
    ]
