# Generated by Django 5.2.11 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_remove_client_charges_mensuelles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activiteimportee",
            name="identifiant_source",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="client",
            name="identifiant_source",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name="activiteimportee",
            constraint=models.UniqueConstraint(fields=("client", "identifiant_source"), name="activite_source_unique_par_client"),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("identifiant_institution_source", "identifiant_source"),
                name="client_source_unique_par_institution",
            ),
        ),
    ]
