# Generated by Django 5.2.11 on 2026-08-13 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RubriqueAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=140)),
                ('mode', models.CharField(choices=[('SAISIE', 'Saisie'), ('CALCUL', 'Calculée'), ('INFORMATION', 'Information')], default='SAISIE', max_length=20)),
                ('type_valeur', models.CharField(choices=[('MONTANT', 'Montant'), ('NOMBRE', 'Nombre'), ('POURCENTAGE', 'Pourcentage'), ('DATE', 'Date'), ('CHOIX', 'Choix'), ('BOOLEEN', 'Oui / non'), ('TEXTE', 'Texte')], default='MONTANT', max_length=20)),
                ('sens', models.CharField(choices=[('CREDIT', "S'ajoute"), ('DEBIT', 'Se retranche'), ('RESULTAT', 'Résultat'), ('NEUTRE', 'Neutre')], default='CREDIT', max_length=20)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('periodicite', models.CharField(choices=[('MENSUELLE', 'Mensuelle'), ('CAMPAGNE', 'Par campagne'), ('ANNUELLE', 'Annuelle'), ('PONCTUELLE', 'Ponctuelle')], default='MENSUELLE', max_length=20)),
                ('source', models.CharField(choices=[('DECLARATIVE', 'Déclarative'), ('IMPORTEE', 'Importée'), ('CALCULEE', 'Calculée')], default='DECLARATIVE', max_length=20)),
                ('obligatoire', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('ordre', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CadreAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('publie_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('code', '-version'),
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FormuleAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=400)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('rubrique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formule', to='cadres.rubriqueanalyse')),
            ],
        ),
        migrations.CreateModel(
            name='SectionAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=120)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cadres.cadreanalyse')),
            ],
            options={
                'ordering': ('ordre', 'id'),
                'unique_together': {('cadre', 'code')},
            },
        ),
        migrations.AddField(
            model_name='rubriqueanalyse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubriques', to='cadres.sectionanalyse'),
        ),
        migrations.CreateModel(
            name='RegleAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('nom', models.CharField(max_length=140)),
                ('condition', models.CharField(max_length=400)),
                ('resultat', models.CharField(choices=[('POINT_ATTENTION', "Point d'attention"), ('POINT_FAVORABLE', 'Point favorable'), ('INFORMATION', 'Information'), ('DOSSIER_INCOMPLET', 'Dossier incomplet')], default='POINT_ATTENTION', max_length=30)),
                ('message', models.CharField(max_length=300)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='cadres.cadreanalyse')),
            ],
            options={
                'ordering': ('ordre', 'id'),
                'unique_together': {('cadre', 'code')},
            },
        ),
    ]
