# Generated by Django 5.2.11 on 2026-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubriqueanalyse',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'Aucun rôle particulier'), ('MARGE_DISPONIBLE', 'Marge disponible'), ('PRESSION_REMBOURSEMENT', 'Pression de remboursement'), ('RESULTAT_ACTIVITE', "Résultat de l'activité")], max_length=30),
        ),
    ]
